version: '3.7'
services:
  full_node:
    build: docker_full_node
    ports:
      - "8444:8444"
  harvester:
    build: docker_harvester
    ports:
      - "8448:8448"
  farmer:
    build: docker_farmer
    ports:
      - "8447:8447"